version: "3"

services:
  php:
    build:
      context: docker/php
      dockerfile: Dockerfile
    user: php
    working_dir: /home/php
    tty: true
    stdin_open: true
    entrypoint: sh
    volumes:
      - ./php:/home/php

  postgres:
    build:
      context: docker/postgres
      dockerfile: Dockerfile
    volumes:
      - ./postgres:/var/lib/postgresql/data

  ngrok:
    build:
      context: docker/ngrok
      dockerfile: Dockerfile
    user: ngrok
    working_dir: /home/ngrok/
    tty: true
    stdin_open: true
    entrypoint: sh
    volumes:
      - ./ngrok:/home/ngrok